# Generated by Django 6.0.7 on 2026-08-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
