# Generated by Django 6.0.7 on 2026-08-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_brand_car_company_rename_name_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
